---
title: "Models for Selected Countries (Jasper)"
author: "Jasper Cheng"
date: "3/3/2021"
output: html_document
---
```{r}
library(dplyr)
library(ggplot2)
```

```{r}
newdata <- read.csv("WHO-COVID-19-global-data.csv")
newdata %>% rename(Date="ï..Date_reported") -> newdata
newdata %>% mutate(CFR=Cumulative_deaths/Cumulative_cases) -> newdata
```

```{r Countries}
egypt=filter(newdata,(Country=="Egypt"))
egypt=egypt[73:172,]
egypt=mutate(egypt,Time=seq(1:100))

china=filter(newdata,(Country=="China"))
china=china[17:116,]
china=mutate(china,Time=seq(1:100))

japan=filter(newdata,(Country=="Japan"))
japan=japan[50:149,]
japan=mutate(japan,Time=seq(1:100))
```

```{r Visualize}
plot(egypt$Time,egypt$CFR)
plot(china$Time,china$CFR)
plot(japan$Time,japan$CFR)
```


```{r}
#For Egypt (choose 3, mod 2 only for comparison)
modegypt2=lm(egypt$CFR~poly(egypt$Time,degree=2,raw=T))
modegypt3=lm(egypt$CFR~poly(egypt$Time,degree=3,raw=T))

plot(egypt$Time,egypt$CFR)
lines(smooth.spline(egypt$Time,predict(modegypt2)),col='red')
lines(smooth.spline(egypt$Time,predict(modegypt3)),col='blue')

plot(modegypt3)
```

```{r}
#For Japan
modjapan2=lm(japan$CFR~poly(japan$Time,degree=4,raw=T))

plot(japan$Time,japan$CFR)
lines(smooth.spline(japan$Time,predict(modjapan2)),col='red')

summary(modjapan2)
plot(modjapan2)
```

```{r}
#For China (since the outliers are quite extreme, you guys could make a decision on what to do)
modchina2=lm(china$CFR~poly(china$Time,degree=4,raw=T))

plot(china$Time,china$CFR)
lines(smooth.spline(china$Time,predict(modchina2)),col='red')

summary(modchina2)
plot(modchina2)
```

```{r}
#For Brazil 
brazildata = final %>% filter(.,Country == "Brazil" & Date >= "2020-03-13" & Date <= "2020-06-20" )
brazildata= mutate(brazildata, time = seq(1:100), CFR= brazildata$Cumulative_deaths/brazildata$Cumulative_cases)

brazil2= lm(brazildata$CFR~poly(brazildata$time, degree=2, raw=T))
summary(brazil2)
plot(brazildata$time, brazildata$CFR)
lines(smooth.spline(brazildata$time,predict(brazil2)),col='blue')

plot(brazil2)
```
```{r}
#For India 
indiadata = final %>% filter(.,Country == "India" & Date >= "2020-03-15" & Date <= "2020-06-22" )
indiadata= mutate(indiadata, time = seq(1:100), CFR= indiadata$Cumulative_deaths/indiadata$Cumulative_cases)

india2= lm(indiadata$CFR~poly(indiadata$time, degree=3, raw=T))
summary(india2)
plot(indiadata$time, indiadata$CFR)
lines(smooth.spline(indiadata$time,predict(india2)),col='blue')

plot(india2)
```
```{r}
#For Indonesia 
indonesiadata = final %>% filter(.,Country == "Indonesia" & Date >= "2020-03-15" & Date <= "2020-06-22" )
indonesiadata= mutate(indonesiadata, time = seq(1:100), CFR= indonesiadata$Cumulative_deaths/indonesiadata$Cumulative_cases)

indonesia2= lm(indonesiadata$CFR~poly(indonesiadata$time, degree=3, raw=T))
summary(indonesia2)
plot(indonesiadata$time, indonesiadata$CFR)
lines(smooth.spline(indonesiadata$time,predict(indonesia2)),col='blue')

plot(indonesia2)
```

```{r}
#Pakistan Data
pakistandata = newdata %>% filter(.,Country == "Pakistan" & Date >= "2020-03-17" & Date <= "2020-06-24" )
pakistandata = mutate(pakistandata, Time = seq(1:100))

pakpoly.model = lm(CFR~ poly(Time, degree = 3 , raw = TRUE), data = pakistandata)

plot(pakistandata$Time, pakistandata$CFR)
lines(smooth.spline(pakistandata$Time,predict(pakpoly.model)),col='blue')

summary(pakpoly.model)
plot(pakpoly.model)
```

```{r}
#Russia Data
russiadata = newdata %>% filter(.,Country == "Russian Federation" & Date >= "2020-03-19" & Date <= "2020-06-26" )
russiadata = mutate(russiadata, Time = seq(1:100))


russpoly.model = lm(CFR~ poly(Time, degree = 4, raw = TRUE), data = russiadata) # Which degee?

plot(russiadata$Time, russiadata$CFR)
lines(smooth.spline(russiadata$Time,predict(russpoly.model)),col='blue')

summary(russpoly.model)
plot(russpoly.model)
```

```{r}
#Turkey Data
turkeydata = newdata %>% filter(.,Country == "Turkey" & Date >= "2020-03-19" & Date <= "2020-06-26" )
turkeydata = mutate(turkeydata, Time = seq(1:100))
turkpoly.model = lm(CFR~ poly(Time, degree = 2, raw = TRUE), data = turkeydata)

plot(turkeydata$Time, turkeydata$CFR)
lines(smooth.spline(turkeydata$Time,predict(turkpoly.model)),col='blue')

summary(turkpoly.model)
plot(turkpoly.model)
```